import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Hello: NextPage = () => {
  const hello = trpc.useQuery(["hello", { text: "client" }]);
  if (!hello.data) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <p>{hello.data.greeting}</p>
    </div>
  );
};

interface Props {
  notes: string;
}

const Home: NextPage<Props> = ({ notes }) => {
  return (
    <div>
      <Head>
        <title>Next.js tRPC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl font-bold underline">Next.js tRPC</div>
      <Hello />
      <div>{notes}</div>
    </div>
  );
};

export default Home;
